In [ ]:
!wget -O training_data_companydata.csv https://www.dropbox.com/s/4sx75202bnfpmw0/training_data_companydata.csv?dl=0

--2022-07-06 18:46:57--  https://www.dropbox.com/s/4sx75202bnfpmw0/training_data_companydata.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.81.18, 2620:100:6031:18::a27d:5112
Connecting to www.dropbox.com (www.dropbox.com)|162.125.81.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/4sx75202bnfpmw0/training_data_companydata.csv [following]
--2022-07-06 18:46:57--  https://www.dropbox.com/s/raw/4sx75202bnfpmw0/training_data_companydata.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc5c1a9207aa82c41dc23860f1ba.dl.dropboxusercontent.com/cd/0/inline/Boma2JxWsWQwb--bO87WfBmbidhRpVYqeH8HmLMi7LhA9yRBPFZXpqOQ3-0eDdg702SMWU44meHpTsd4uoYkjZaeKAXWFvGcdJtlj7Hiy4RZyFSp1QE84z_o50DKP8Ui02Afs4rz1H4se6yhJjeBZq0EErbt23FlsbHA89_nuac0Xw/file# [following]
--2022-07-06 18:46:58--  https://uc5c1a9207aa82c41dc23860f1ba.dl.dropboxusercontent.com/cd/0/inline/Boma2JxWsWQwb--bO87WfBmbidhRpVYqeH8HmLMi7LhA9yRBPFZXpqOQ3-0eDdg702SMWU44meHpTsd4uoYkjZaeKAXWFvGcdJtlj7Hiy4RZyFSp1QE84z_o50DKP8Ui02Afs4rz1H4se6yhJjeBZq0EErbt23FlsbHA89_nuac0Xw/file
Resolving uc5c1a9207aa82c41dc23860f1ba.dl.dropboxusercontent.com (uc5c1a9207aa82c41dc23860f1ba.dl.dropboxusercontent.com)... 162.125.80.15, 2620:100:6031:15::a27d:510f
Connecting to uc5c1a9207aa82c41dc23860f1ba.dl.dropboxusercontent.com (uc5c1a9207aa82c41dc23860f1ba.dl.dropboxusercontent.com)|162.125.80.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5829709 (5.6M) [text/plain]
Saving to: ‘training_data_companydata.csv’

training_data_compa 100%[===================>]   5.56M  7.21MB/s    in 0.8s

2022-07-06 18:46:59 (7.21 MB/s) - ‘training_data_companydata.csv’ saved [5829709/5829709]

In [ ]:
from pandas import read_csv
import pandas as pd
import numpy as np

In [ ]:
# Method to get level_1 labels from level_2 labels
max_length=0
def label_types (row):
  global max_length
  length = len(row['Label'])
  max_length = max(max_length,length)
  if length == 4 :
    return row['Label'][0:3]
  else: return row['Label']

In [ ]:
# Method to get Performance labels from level_2 labels
def label_performance (row):
  length = len(row['Label'])
  if length == 2 :
    return 0
  else: return 1

In [ ]:
training_data = pd.read_csv('training_data_companydata.csv')

In [ ]:
training_data

,Unnamed: 0,Unnamed: 0.1,Column1,Causal-relation ID,Causal-relation text,Variables,Role in the text,expertA_level0,expertA_level1,expertB_level2,expertB_level0,expertB_level1,expertB_level2.1,Label,performance,Label1,Level1,Label2,Level2
0,0,0,0,AFLAC_Wyatt_1,When a policyholder or insured gets sick or ...,cash benefits fairly and promptly for eligible...,outcome,P,CUS,CUS4,P,CUS,CUS4,P,1,CUS,0,CUS4,3
1,1,1,1,AFLAC_Wyatt_1,When a policyholder or insured gets sick or ...,policyholder or insured gets sick or hurt,cause,NP,NP,NP,NP,NP,NP,NP,0,NP,3,NP,11
2,2,2,3,AFLAC_Wyatt_2,"During 2020, in response to the onset and de...",to digital sales methods,outcome,NP,NP,NP,NP,NP,NP,NP,0,NP,3,NP,11
3,3,3,4,AFLAC_Wyatt_2,"During 2020, in response to the onset and de...",related digital investments,outcome,NP,NP,NP,NP,NP,NP,NP,0,NP,3,NP,11
4,4,4,5,AFLAC_Wyatt_2,"During 2020, in response to the onset and de...",the onset and development of the global COVID...,cause,NP,NP,NP,NP,NP,NP,NP,0,NP,3,NP,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14503,14503,14503,21155,ZION_Golnaz_Alice_151,We reduced share-based compensation expense by...,using a valuation model to estimate a liquidit...,cause,NP,NP,NP,NP,NP,NP,NP,0,NP,3,NP,11
14504,14504,14504,21157,ZION_Golnaz_Alice_151,During 2018 after filing its 2017 federal and ...,Bank finalized its analysis of all net DTAs th...,outcome,P,UC,UC,P,UC,UC,P,1,UC,5,UC,15
14505,14505,14505,21158,ZION_Golnaz_Alice_151,During 2018 after filing its 2017 federal and ...,the Act.,cause,NP,NP,NP,NP,NP,NP,NP,0,NP,3,NP,11
14506,14506,14506,21160,ZION_Golnaz_Alice_151,The following schedule does not present total ...,"presents average loans, average deposits and i...",outcome,P,INV,INV1,P,INV,INV1,P,1,INV,2,INV1,7
14507,14507,14507,21161,ZION_Golnaz_Alice_151,The following schedule does not present total ...,these are the metrics that management uses whe...,cause,NP,NP,NP,NP,NP,NP,NP,0,NP,3,NP,11

In [ ]:
training_data_expert_performance = training_data.iloc[:,14:15]

In [ ]:
training_data_expert_level1 = training_data.iloc[:,16:17]

In [ ]:
training_data_expert_level2 = training_data.iloc[:,18:19]

In [ ]:
training_data_text = training_data.iloc[:,5]

In [ ]:
training_data_text

0        cash benefits fairly and promptly for eligible...
1                policyholder or insured gets sick or hurt
2                                to digital sales methods
3                             related digital investments
4         the onset and development of the global COVID...
                               ...
14503    using a valuation model to estimate a liquidit...
14504    Bank finalized its analysis of all net DTAs th...
14505                                             the Act.
14506    presents average loans, average deposits and i...
14507    these are the metrics that management uses whe...
Name: Variables, Length: 14508, dtype: object

In [ ]:
training_datalabel_expert_final = pd.concat([training_data_expert_performance,training_data_expert_level1,training_data_expert_level2],axis=1)

In [ ]:
training_datalabel_expert_final

       performance  Level1  Level2
0                1       0       3
1                0       3      11
2                0       3      11
3                0       3      11
4                0       3      11
...            ...     ...     ...
14503            0       3      11
14504            1       5      15
14505            0       3      11
14506            1       2       7
14507            0       3      11

[14508 rows x 3 columns]

In [ ]:
from sklearn.linear_model import LogisticRegression
import sklearn.model_selection
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline, FeatureUnion

In [ ]:
from pandas import read_csv
import pandas as pd
import math
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
import torch

In [ ]:
k=5
seed = 1
kf = StratifiedKFold(n_splits=k,random_state=seed, shuffle=True)
label_count = {'performance':2,'Level1':5,'Level2':16}
for label, count in label_count.items():
  x=training_data
  y=training_data[label]
  for train_index, val_index in kf.split(x,y):
    train_texts, val_texts =x['Variables'].iloc[train_index],x['Variables'].iloc[val_index]
    train_labels, val_labels =y.iloc[train_index],y.iloc[val_index]
    print('train_labels',train_labels)

train_labels 0        1
2        0
3        0
4        0
5        0
        ..
14502    1
14503    0
14505    0
14506    1
14507    0
Name: performance, Length: 11606, dtype: int64
train_labels 1        0
4        0
5        0
6        0
7        0
        ..
14502    1
14503    0
14504    1
14506    1
14507    0
Name: performance, Length: 11606, dtype: int64
train_labels 0        1
1        0
2        0
3        0
4        0
        ..
14501    0
14502    1
14503    0
14504    1
14505    0
Name: performance, Length: 11606, dtype: int64
train_labels 0        1
1        0
2        0
3        0
5        0
        ..
14503    0
14504    1
14505    0
14506    1
14507    0
Name: performance, Length: 11607, dtype: int64
train_labels 0        1
1        0
2        0
3        0
4        0
        ..
14501    0
14504    1
14505    0
14506    1
14507    0
Name: performance, Length: 11607, dtype: int64
train_labels 0        0
1        3
2        3
3        3
5        3
        ..
14500    5
14501    3
14503    3
14505    3
14506    2
Name: Level1, Length: 11606, dtype: int64
train_labels 0        0
1        3
2        3
3        3
4        3
        ..
14497    3
14499    3
14502    2
14504    5
14507    3
Name: Level1, Length: 11606, dtype: int64
train_labels 0        0
2        3
3        3
4        3
6        3
        ..
14503    3
14504    5
14505    3
14506    2
14507    3
Name: Level1, Length: 11606, dtype: int64
train_labels 0        0
1        3
4        3
5        3
6        3
        ..
14503    3
14504    5
14505    3
14506    2
14507    3
Name: Level1, Length: 11607, dtype: int64
train_labels 1        3
2        3
3        3
4        3
5        3
        ..
14503    3
14504    5
14505    3
14506    2
14507    3
Name: Level1, Length: 11607, dtype: int64
train_labels 1        11
2        11
3        11
4        11
5        11
         ..
14502     7
14503    11
14505    11
14506     7
14507    11
Name: Level2, Length: 11606, dtype: int64
train_labels 0         3
1        11
2        11
3        11
5        11
         ..
14501    11
14503    11
14504    15
14505    11
14506     7
Name: Level2, Length: 11606, dtype: int64
train_labels 0         3
1        11
2        11
4        11
7        11
         ..
14502     7
14504    15
14505    11
14506     7
14507    11
Name: Level2, Length: 11606, dtype: int64
train_labels 0         3
3        11
4        11
5        11
6        11
         ..
14501    11
14502     7
14503    11
14504    15
14507    11
Name: Level2, Length: 11607, dtype: int64
train_labels 0         3
1        11
2        11
3        11
4        11
         ..
14503    11
14504    15
14505    11
14506     7
14507    11
Name: Level2, Length: 11607, dtype: int64

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  UserWarning,

In [ ]:
k=5
seed = 1
kf = StratifiedKFold(n_splits=k,random_state=seed, shuffle=True)
label_count = {'performance':2,'Level1':5,'Level2':16}
for label, count in label_count.items():
  x=training_data
  y=training_data[label]
  metrics=[]
  i=1
  for train_index, val_index in kf.split(x,y):
    train_texts, val_texts =x['Variables'].iloc[train_index],x['Variables'].iloc[val_index]
    train_labels, val_labels =y.iloc[train_index],y.iloc[val_index]
    list_text = []
    for words in train_texts:
      list_text.append(words)

    # Preprocessing data to feed into MultinomialNB Classifier
    # Tried ngram_range=[1,1],[2,2],[3,3]
    count_vect = CountVectorizer(ngram_range=[1,3])
    tfidf_transformer=TfidfTransformer()

    # Pipeline using CountVectorizer and TfidfTransformer
    pipeline = Pipeline([('count_vect',count_vect),('tfidf_transformer',tfidf_transformer)])
    pipeline_output = pipeline.fit_transform(list_text)
    param_grid_ = {'C': [1e-5, 1e-3, 1e-1, 1e0, 1e1, 1e2]}
    clf = GridSearchCV(LogisticRegression(solver='lbfgs', max_iter=1000, class_weight='balanced'), cv=5, param_grid=param_grid_).fit(pipeline_output, train_labels)
    # Evaluation Model performance on the Test data
    sentence_list = val_texts.to_list()
    pipeline_test = Pipeline([('count_vect',count_vect),('tfidf_transformer',tfidf_transformer)])
    pipeline_test_output = pipeline_test.transform(sentence_list)
    predicted = clf.predict(pipeline_test_output)

    # #Predicting Causal variables into Performance and Non Performance groups
    # variables_list = merged_causal_statements['Variables'].to_list()
    # pipeline_causal=pipeline_test.transform(variables_list)
    # predicted_causal = clf.predict(pipeline_causal)
    # classification_prediction_causal_list =[]
    # for variable, classification in zip(variables_list, predicted_causal):
    #   classification_prediction_causal_list.append(classification)

    classification_prediction_list =[]
    for sentence, classification in zip(sentence_list, predicted):
      classification_prediction_list.append(classification)
    # Naive_Bayes Model metrics
    classification_list = val_labels.to_list()
    indices = val_index
    training_data.loc[indices, "Logistic_{}_Predictions".format(label)]=classification_prediction_list
    # # merged_causal_statements["Logistic_{}_Predictions_{}".format(label,i)]=classification_prediction_causal_list
    #i = i+1

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,

In [ ]:
print(classification_prediction_list)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 2, 2, 5, 5, 5, 2, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 3, 5, 2, 5, 5, 5, 5, 5, 5, 5, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 5, 2, 5, 5, 5, 5, 2, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 2, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 8, 5, 5, 5, 5, 5, 5, 2, 2, 5, 5, 2, 2, 5, 2, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 2, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 2, 2, 5, 5, 5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 8, 5, 5, 5, 5, 5]

In [ ]:
#entire data

In [ ]:
print("Logistic")
print("PERFORMANCE")
print(classification_report(training_data['performance'], training_data['Logistic_performance_Predictions'], zero_division = 1))
print("Label_num_level_1")
print(classification_report(training_data['Level1'], training_data['Logistic_Level1_Predictions'], zero_division = 1))
print("Label_num_level_2")
print(classification_report(training_data['Level2'], training_data['Logistic_Level2_Predictions'], zero_division = 1))

Logistic
PERFORMANCE
              precision    recall  f1-score   support

           0       0.94      0.93      0.94     12532
           1       0.58      0.65      0.62      1976

    accuracy                           0.89     14508
   macro avg       0.76      0.79      0.78     14508
weighted avg       0.90      0.89      0.89     14508

Label_num_level_1
              precision    recall  f1-score   support

           0       0.11      0.06      0.08        31
           1       0.61      0.52      0.56       204
           2       0.56      0.70      0.62      1013
           3       0.94      0.93      0.94     12532
           4       0.22      0.11      0.15        35
           5       0.36      0.32      0.34       693

    accuracy                           0.88     14508
   macro avg       0.47      0.44      0.45     14508
weighted avg       0.88      0.88      0.88     14508

Label_num_level_2
              precision    recall  f1-score   support

           0       0.40      0.20      0.27        10
           1       0.25      0.17      0.20         6
           2       0.00      0.00      0.00         4
           3       0.00      0.00      0.00        11
           4       0.75      0.67      0.71         9
           5       0.57      0.51      0.54       188
           6       0.60      0.86      0.71         7
           7       0.53      0.69      0.60       897
           8       0.61      0.54      0.57        78
           9       0.29      0.13      0.18        15
          10       0.38      0.26      0.31        23
          11       0.94      0.93      0.94     12532
          12       0.18      0.27      0.21        11
          13       1.00      0.00      0.00         2
          14       0.31      0.18      0.23        22
          15       0.34      0.32      0.33       693

    accuracy                           0.87     14508
   macro avg       0.45      0.36      0.36     14508
weighted avg       0.88      0.87      0.87     14508